[cursor]
blink_interval = 700

[cursor.style]
blinking = "On"
shape = "Block"
[shell]

program = "/bin/zsh"
args = ["-l"]

[font]
size = 19

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
blur = true

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = false

[window.class]
general = "Alacritty"
instance = "Alacritty"

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Copy" },
{ mouse = "Middle", mods = "Control", action = "Paste" },
]



[keyboard]
bindings = [
{ key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" },
{ key = "k", mods = "Alt", action = "ScrollLineUp" },
{ key = "j", mods = "Alt", action = "ScrollLineDown" },
]

[colors]
draw_bold_text_with_bright_colors = true

# Colors (Alabaster Dark)
# author tonsky

[colors.primary]
background = '#0E1415'
foreground = '#FFFFFF'

[colors.cursor]
text = '#0E1415'
cursor = '#FFFFFF'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#eb0000'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'
